SELECT nombre FROM producto;
SELECT nombre,precio  FROM producto;
SELECT *  FROM producto;
SELECT nombre,precio EUROS, (precio*1.09) USD  FROM producto;
SELECT (nombre) 'Nom de producto' ,(precio) Euros, (precio*1.09) Dòlars  FROM producto; 
SELECT upper(nombre),precio  FROM producto; 
SELECT lower(nombre),precio  FROM producto; 
SELECT nombre, CONCAT(LEFT(upper(nombre), 2)) LETRAS FROM fabricante;
SELECT nombre, round(precio) FROM producto;
SELECT nombre, truncate(precio,0) FROM producto;
SELECT fabricante.codigo FROM fabricante INNER JOIN producto ON fabricante.codigo = codigo_fabricante;
SELECT distinct(fabricante.codigo) FROM fabricante INNER JOIN producto ON fabricante.codigo = codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante WHERE codigo >= 4;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT producto.nombre, precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo = codigo_fabricante;
SELECT producto.nombre, precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo = codigo_fabricante ORDER BY fabricante.nombre;
SELECT P.codigo, P.nombre, F.codigo, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante;
SELECT P.nombre, P.precio, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante ORDER BY P.precio ASC LIMIT 1;
SELECT P.nombre, P.precio, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante ORDER BY P.precio DESC LIMIT 1;
SELECT P.codigo, P.nombre, P.precio, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante WHERE F.nombre = 'Lenovo';
SELECT P.codigo, P.nombre, P.precio, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante WHERE F.nombre = 'Crucial' AND P.precio > 200;
SELECT P.codigo, P.nombre, P.precio, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante WHERE F.nombre = 'Asus' OR F.nombre = 'Hewlett-Packard' OR F.nombre ='Seagate';
SELECT P.codigo, P.nombre, P.precio, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante WHERE F.nombre IN ('Asus','Hewlett-Packard','Seagate');
SELECT P.nombre, P.precio, F.nombre FROM producto P  INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante WHERE F.nombre LIKE '%e';
SELECT P.nombre, P.precio, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante WHERE F.nombre LIKE '%w%';
SELECT P.nombre, P.precio, F.nombre FROM producto P INNER JOIN fabricante F ON F.codigo = P.codigo_fabricante WHERE P.precio >= 180 ORDER BY P.precio DESC, P.nombre ASC;
SELECT distinct F.codigo, F.nombre FROM fabricante F INNER JOIN producto P ON F.codigo = P.codigo_fabricante;
SELECT distinct F.codigo, F.nombre, P.nombre PRODUCTO FROM fabricante F  LEFT JOIN producto P ON F.codigo = P.codigo_fabricante;
SELECT distinct F.codigo, F.nombre, P.nombre PRODUCTO FROM fabricante F  LEFT JOIN producto P ON F.codigo = P.codigo_fabricante WHERE P.nombre IS NULL;
SELECT P.nombre Productos FROM fabricante F, producto P WHERE F.codigo = P.codigo_fabricante AND F.nombre = 'Lenovo';
SELECT P.codigo, P.nombre, P.precio, P.codigo_fabricante  FROM fabricante F, producto P WHERE F.codigo = P.codigo_fabricante AND F.nombre = 'Lenovo' AND P.precio = 559;
SELECT P.nombre FROM fabricante F, producto P WHERE F.codigo = P.codigo_fabricante AND F.nombre = 'Lenovo' ORDER BY P.precio DESC LIMIT 1;
SELECT P.nombre  FROM fabricante F, producto P WHERE F.codigo = P.codigo_fabricante AND F.nombre = 'Hewlett-Packard' ORDER BY P.precio ASC LIMIT 1;
SELECT *  FROM producto WHERE precio >= 559;
SELECT *  FROM producto WHERE precio >= 223.99 AND codigo_fabricante = 1;

SELECT apellido1, apellido2, nombre FROM PERSONA WHERE tipo = 'alumno' ORDER BY apellido1, apellido2, nombre ASC;
SELECT nombre,apellido1, apellido2 FROM persona WHERE tipo = 'alumno' AND telefono IS NULL; 
SELECT nombre,apellido1, apellido2,fecha_nacimiento FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento >= '1999-01-01' AND fecha_nacimiento <= '1999-12-31'; 
SELECT * FROM persona WHERE tipo = 'profesor' AND telefono IS NULL AND nif LIKE '%K%'; 
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7; 
SELECT C.apellido1, C.apellido2, C.nombre, E.nombre FROM persona C, profesor O, departamento E WHERE C.id = O.id_profesor AND O.id_departamento = E.id AND tipo = 'profesor' ORDER BY C.apellido1, C.apellido2, C.nombre ASC;
SELECT DISTINCT D.nombre, C.anyo_inicio, C.anyo_fin FROM persona A, alumno_se_matricula_asignatura B, curso_escolar C, asignatura D WHERE A.id = B.id_alumno AND A.tipo = 'alumno' AND A.nif = '26902806M'  AND B.id_curso_escolar = C.id AND B.id_curso_escolar = D.curso;
SELECT DISTINCT C.nombre FROM asignatura A, profesor B, departamento C WHERE A.id_profesor = B.id_profesor AND A.id_grado = 4 AND A.id_profesor IS NOT NULL  AND B.id_departamento = C.id;
SELECT DISTINCT A.apellido1, A.apellido2, A.nombre FROM persona A, alumno_se_matricula_asignatura B WHERE A.id = B.id_alumno AND B.id_curso_escolar = 5;

SELECT departamento.nombre, persona.apellido1,persona.apellido2,persona.nombre FROM profesor LEFT JOIN persona ON profesor.id_profesor = persona.id  LEFT JOIN departamento ON profesor.id_departamento = departamento.id     ORDER BY departamento.id, persona.apellido1,persona.apellido2,persona.nombre, profesor.id_departamento; 
SELECT profesor.id_profesor, departamento.id FROM profesor LEFT JOIN departamento ON profesor.id_departamento = departamento.id; 
SELECT departamento.id, departamento.nombre FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento WHERE id_profesor IS NULL;
SELECT profesor.id_profesor FROM profesor LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id IS NULL;
SELECT asignatura.id, asignatura.nombre FROM profesor RIGHT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE profesor.id_profesor IS NULL;
SELECT departamento.id, departamento.nombre FROM profesor RIGHT JOIN departamento ON profesor.id_departamento = departamento.id WHERE profesor.id_profesor IS NULL;

SELECT COUNT(tipo) FROM persona WHERE tipo = 'alumno';
SELECT COUNT(tipo) FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento >= '1999-01-01' AND fecha_nacimiento <= '1999-12-31';
SELECT COUNT(id_departamento) FROM profesor GROUP BY id_departamento; 
SELECT B.nombre, C.nombre FROM profesor A, departamento B, persona C WHERE A.id_profesor = C.id AND C.tipo = 'profesor' AND A.id_departamento = B.id ORDER BY C.nombre;
SELECT departamento.id, departamento.nombre, id_profesor FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento;
SELECT grado.nombre, asignatura.nombre FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado ORDER BY asignatura.nombre ASC;
SELECT id_grado , G.nombre, A.nombre FROM asignatura A INNER JOIN grado G ON G.id = A.id_grado WHERE id_grado=4;
SELECT G.nombre, tipo, count(creditos) AS TOTAL FROM asignatura A, grado G WHERE A.id_grado = G.id GROUP BY tipo,G.nombre;
SELECT  C.anyo_inicio, COUNT(A.id_alumno) FROM alumno_se_matricula_asignatura A INNER JOIN asignatura S ON A.id_asignatura = S.id INNER JOIN curso_escolar C ON C.id = A.id_curso_escolar GROUP BY  C.anyo_inicio, A.id_alumno;
SELECT  P.id, P.apellido1, P.apellido2, P.nombre, COUNT(A.id_profesor) NumeroAsignaturas FROM persona P LEFT JOIN asignatura A ON A.id_profesor = P.id WHERE P.tipo = 'profesor' GROUP BY  P.id, P.apellido1, P.apellido2, P.nombre, A.id_profesor ORDER BY A.id_profesor;
SELECT  * FROM persona WHERE tipo = 'alumno' ORDER BY fecha_nacimiento LIMIT 1;
SELECT PE.id, PE.apellido1, PE.apellido2, PE.nombre FROM persona PE, profesor PR WHERE PE.id = PR.id_profesor AND PE.tipo = 'profesor' AND PE.id NOT IN (3, 14) GROUP BY PE.id, PE.apellido1, PE.apellido2, PE.nombre;